# Generated by Django 5.2.4 on 2025-07-17 19:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollperiod',
            unique_together={('start_date', 'end_date')},
        ),
        migrations.AlterField(
            model_name='bonustype',
            name='calculation_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Salary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bonustype',
            name='default_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount or percentage value', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bonustype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deductiontype',
            name='calculation_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Salary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='deductiontype',
            name='default_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount or percentage value', max_digits=10),
        ),
        migrations.AlterField(
            model_name='deductiontype',
            name='is_taxable',
            field=models.BooleanField(default=True, help_text='Whether this deduction affects taxable income'),
        ),
        migrations.AlterField(
            model_name='deductiontype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollbonus',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollhistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CALCULATED', 'Calculated'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('MODIFIED', 'Modified')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollhistory',
            name='performed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='name',
            field=models.CharField(help_text="e.g., 'January 2024', 'Q1 2024'", max_length=100),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='pay_date',
            field=models.DateField(help_text='Date when salaries will be paid'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='period_type',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='MONTHLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='emailed_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='generated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payslip',
            name='payroll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='payroll.payroll'),
        ),
        migrations.AlterField(
            model_name='taxslab',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='taxslab',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank for highest slab', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='taxslab',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='taxslab',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, help_text='Tax rate as percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
